spring.application.name=taskflow

spring.datasource.url=jdbc:mysql://thomas.proxy.rlwy.net:42185/railway
spring.datasource.username=root
spring.datasource.password=hkAycPQZwKFGphGjLdqpaxOJtpNVHAwT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

jwt.secret=mySuperSecretKeyForJwtTokenGeneration123!